### ISSUE TITLE
New step not getting focus and global editor not updated

### ISSUE THREAD

**Issue by carlson** [b4rtaz/sequential-workflow-designer#1]
Great job on this project!

Not sure if this is intended behavior but after dragging a new step into the workflow I expected the newly added step to have focus and the appropriate step editor rendered. Instead, the focus stays on the global editor and doesn't reflect the underlying definition change.

Steps to Repro (version 0.1.6):

* Start with an empty definition in the fullscreen example (the global editor is shown)
* Add a step from the toolbox (focus remains on the global editor showing the empty definition even though onDefinitionChanged is called on the designer)
* Change focus to the newly added step and then back to the overall process (globalEditorProvider is called and the current state of the definition is now rendered)

**Comment by b4rtaz** [comment]
I think this is a good idea. It should increase the speed of the designer's usage. I've just release 0.1.7, this version contains that feature.

**Comment by carlson** [comment]
0.1.7 works great, thanks!
