### ISSUE TITLE
Switch to a previous step

### ISSUE THREAD

**Issue by gaurav-mtalkz** [b4rtaz/sequential-workflow-designer#2]
Hello,

I was exploring this library for a flowchart builder I am trying to make.

I am just wondering if there is a way to connect switch to existing steps, instead of redefining steps again?

I am trying to use it kind of multi outcome loop, until a specific condition is met.

Please let me know if this is possible.

Thanks!

**Comment by b4rtaz** [comment]
I'm not sure that I understood correctly.

```
[loop] {
   [send_email_task]
   [loop] {
       [send_email_task]
       [break_loop_task, condition = "if x == 1"]
   }
   [break_loop_task, condition = "if x == 1"]
   [send_email-task]
}
```

So you don't want to duplicate the condition in breaking tasks?

**Comment by gaurav-mtalkz** [comment]
Actually I wish to go back to different points in the flow depending on the value of x. Say,
if x == 1: go to step 1
if x == 2: go to step 2
if x == 3: go to step 3
if x == 4: go to step 4
else continue below

**Comment by b4rtaz** [comment]
I think that depends on an implementation of your state machine. You could create a `jumpIf` step.

```
[loop] {
   [jumpIf, targetId=0x1, condition="if x == 1"]
   [jumpIf, targetId=0x2, condition="if x == 2"]
   [jumpIf, targetId=0x3, condition="true"] // always jump

   [sendEmail, id=0x1]
   [writeFile, id=0x2]

   [log, id=0x3]
}
```

**Comment by gaurav-mtalkz** [comment]
I think I'll create a switch-to step in a similar manner. Could you help me with a few pointers as to which would be the right place to add this step type?

**Comment by b4rtaz** [comment]
It could be hard. But you can look at [this example](https://b4rtaz.github.io/sequential-workflow-designer/examples/live-testing.html). I think here not too much is needed to add jumps.

**Comment by gaurav-mtalkz** [comment]
Thanks! I'm currently exploring ways to add unconditional branches. For
example, in switch I may have to execute a step, and then may have to go to
a previous step.
