### ISSUE TITLE
Query: adding constraints on drag and drop

### ISSUE THREAD

**Issue by gaurav-mtalkz** [b4rtaz/sequential-workflow-designer#3]
Hello,

How can I enforce constraint on drag and drop area for a particular step type.
Say I want the particular task step (identified by step.type) to be added only at the end of switch node branches and nowhere else then how can such constraint be enforced?

Thanks!

**Comment by b4rtaz** [comment]
I will add the constraint feature soon. Thanks for feedback.

**Comment by gaurav-mtalkz** [comment]
Thanks!

While you are at it, kindly also include the step.type to class of the container div. This allows for styling the different step types (with same component types) differently using CSS.

Here is what I've done in the designer.js line #1352 (JS version from CDN) for this:
```
class: `sqd-task-group sqd-task-${step.type}`
```
in the method `TaskStepComponentView::create()`

**Comment by b4rtaz** [comment]
Check [this release](https://github.com/b4rtaz/sequential-workflow-designer/releases/tag/v0.2.0).

**Comment by gaurav-mtalkz** [comment]
This looks amazing!

Thanks,
Gaurav
