### ISSUE TITLE
Undo/Redo - Customize Control Bar

### ISSUE THREAD

**Issue by reramjiawan** [b4rtaz/sequential-workflow-designer#4]
Hello,

Thank you very much for this tool it's very customizable and does the job!

However what is really missing is an undo/redo button preferably you can add custom buttons to the control bar just like how you can customize the toolbox.

Kind regards,

Ravindre

**Comment by b4rtaz** [comment]
Hi! Check 0.2.1 version ([demo](https://b4rtaz.github.io/sequential-workflow-designer/examples/fullscreen.html)).
