### ISSUE TITLE
user defined number of branches for the switch

### ISSUE THREAD

**Issue by gpetrov** [b4rtaz/sequential-workflow-designer#5]
Currently the switch component allows only predefines number of branches.

When using as `select/case 1/case 2/case xx` it is much desirable to let the user define visually how many cases he wants. So there must be visually a possibility to add more cases.

So a new option for user defined branches will be really welcome.

**Comment by b4rtaz** [comment]
I think this is a responsibility of your custom step editor. I've added a demo to [this example](https://b4rtaz.github.io/sequential-workflow-designer/examples/fullscreen.html) (check the `if` step).

**Comment by gpetrov** [comment]
Well in the 'if' step you have only predefined values like true and false.

If a real switch is to be implemented the user should have a way to add multiple case values inline.

So initially it might start with a single value and default but there should be a + sign somewhere for example to add extra case value.

**Comment by b4rtaz** [comment]
@gpetrov I think you didn't understand me. I mean you can control how many branches the switch step has from the step editor. I've prepared a dedicated example [here](https://b4rtaz.github.io/sequential-workflow-designer/examples/fullscreen.html). So by using this approach you can add dynamically branches as you want.

```js
if (checked) {
   step.branches['catch'] = [];
} else {
   delete step.branches['catch'];
}
editorContext.notifyChildrenChanged();
```

![catch-branch-designer](https://user-images.githubusercontent.com/12797776/201771157-95055355-e155-45ba-be21-bfb4ec7da5c5.gif)

**Comment by gpetrov** [comment]
Oh I see now. Yes that is a good way indeed. I as looking for inline icon action to do this but this way is fine indeed.

Thank you great work!

**Comment by morning-star-001** [comment]
Quick one, how to add branches to a switch component type.

`const ifModel = sequentialWorkflowEditorModel.createStepModel('if', 'switch', step => {

                step.property('expression').value(sequentialWorkflowEditorModel.createStringValueModel({
                    defaultValue: "lorep isium"
                }));

                // how can branches be added


            });`

**Comment by morning-star-001** [comment]
The error I am recieving after the snippet below is _"Branches configuration is not set for if"_

`const ifModel = sequentialWorkflowEditorModel.createBranchedStepModel('if', 'switch', step => {

                step.property('expression').value(sequentialWorkflowEditorModel.createStringValueModel({
                    defaultValue: "lorep"
                }));


            });`

**Comment by b4rtaz** [comment]
@morning-star-001 please chek [this code](https://github.com/nocode-js/sequential-workflow-editor/blob/53c9d33b368c4a248366267f8e94040910d99a17/demos/webpack-app/src/playground/model/if-step-model.ts#L53):

```ts
step.branches().value(
  createBranchesValueModel({
    branches: {
      true: [],
      false: []
    }
  })
);
```

But this way is not dynamic. Dynamic branches are possible with the [branches value editor](https://nocode-js.com/docs/sequential-workflow-editor/additional-editors/branches) (pro) or the [dependant value model](https://nocode-js.com/docs/sequential-workflow-editor/value-models/dependent) (pro). You can check [this online demo](https://nocode-js.com/examples/sequential-workflow-editor-pro/webpack-pro-app/public/editors.html#branches).
