### ISSUE TITLE
Center switch step after adding branches

### ISSUE THREAD

**Issue by liljefelt** [b4rtaz/sequential-workflow-designer#6]
Hi, first off this library is amazing, well done!

The current Switch step behaviour when adding branches is to add them to the right, and I'm wondering if it is possible to "center" a switch step automatically after programmatically adding branches?

Default behaviour:
http://46.246.30.230/github/uncentered-step.jpg

What I'm looking for:
http://46.246.30.230/github/centered-step.jpg

Thanks!

**Comment by b4rtaz** [comment]
Hi @liljefelt! I've just improved the switch step. Check [this example](https://b4rtaz.github.io/sequential-workflow-designer/examples/fullscreen.html).

**Comment by liljefelt** [comment]
That is beautiful - thank you!!
